---
name: Lint

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".gitignore"

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: yamllint
        run: yamllint .

      - name: ansible-lint
        run: ansible-lint
